services:
  sqlserver:
    container_name: budgexa-sqlserver
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - SA_PASSWORD=${SA_PASSWORD}
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    networks:
      - budgexa-net
    restart: always

  budgexaapi:
    container_name: budgexa-api
    build:
      context: .
      dockerfile: backend/BudgexaApi/src/Budgexa.API/Dockerfile
    networks:
      - budgexa-net
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=${CONNECTION_STRING}
      - JwtSettings__Secret=${JWT_SECRET}
      - Ollama__BaseUrl=http://192.168.1.69:11434
      - Ollama__DefaultModel=qwen3-coder:30b
      - ASPNETCORE_URLS=http://+:80
      - Cors__AllowedOrigins__0=https://budgexaclient.duckdns.org
      - FileStorage__ProfileImagesPath=/app/uploads/profile-images
      - FileStorage__BaseUrl=https://budgexaclient.duckdns.org/api
    volumes:
      - profile-images:/app/uploads/profile-images
    depends_on:
      - sqlserver
    restart: always

  budgexa-client:
    container_name: budgexa-client
    build:
      context: ./frontend/budgexa-client
      dockerfile: Dockerfile.prod
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - certbot-etc:/etc/letsencrypt:ro
      - certbot-var:/var/lib/letsencrypt
      - certbot-www:/var/www/certbot:ro
    networks:
      - budgexa-net
    depends_on:
      - budgexaapi
    restart: always

  certbot:
    container_name: budgexa-certbot
    image: certbot/certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - certbot-www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    networks:
      - budgexa-net

networks:
  budgexa-net:
    driver: bridge

volumes:
  profile-images:
  certbot-etc:
    external: true
    name: budgexa_certbot-etc
  certbot-var:
    external: true
    name: budgexa_certbot-var
  certbot-www:
    external: true
    name: budgexa_certbot-www