namespace Budgexa.Infrastructure.Services.Pdf.Invoices;

internal static class InvoicePdfLabelsFactory
{
    public static InvoicePdfLabels Create(string languageCode) => languageCode switch
    {
        "es" => new InvoicePdfLabels(
            Title: "Factura",
            CustomerLabel: "Cliente",
            PhoneLabel: "Teléfono",
            EmailLabel: "Email",
            DateLabel: "Fecha",
            DueDateLabel: "Vencimiento",
            ItemColumn: "Descripción",
            QuantityColumn: "Cantidad",
            UnitPriceColumn: "Precio Unit.",
            DiscountColumn: "Dto. (%)",
            TaxColumn: "IVA (%)",
            WithholdingColumn: "Retención (%)",
            TotalColumn: "Total",
            SubTotalLabel: "Subtotal",
            TaxTotalLabel: "Total Impuestos",
            WithholdingTotalLabel: "Total Retención",
            GrandTotalLabel: "Total General",
            AmountPaidLabel: "Pagado",
            AmountDueLabel: "Pendiente",
            PaymentMethodLabel: "Método de pago",
            PaymentReferenceLabel: "Referencia",
            PaymentInfoLabel: "Información de pago",
            NotesLabel: "Notas",
            FooterText: "Gracias por su confianza. Esta factura ha sido generada automáticamente.",
            SignatureLabel: "Firma",
            PaymentMethodBankTransfer: "Transferencia bancaria",
            PaymentMethodCash: "Efectivo",
            PaymentMethodCard: "Tarjeta",
            PaymentMethodDirectDebit: "Domiciliación",
            PaymentMethodBizum: "Bizum",
            PaymentMethodOther: "Otro"),

        "de" => new InvoicePdfLabels(
            Title: "Rechnung",
            CustomerLabel: "Kunde",
            PhoneLabel: "Telefon",
            EmailLabel: "E-Mail",
            DateLabel: "Datum",
            DueDateLabel: "Fällig am",
            ItemColumn: "Beschreibung",
            QuantityColumn: "Menge",
            UnitPriceColumn: "Einzelpreis",
            DiscountColumn: "Rabatt (%)",
            TaxColumn: "MwSt. (%)",
            WithholdingColumn: "Quellensteuer (%)",
            TotalColumn: "Gesamt",
            SubTotalLabel: "Zwischensumme",
            TaxTotalLabel: "Steuern Gesamt",
            WithholdingTotalLabel: "Quellensteuer Gesamt",
            GrandTotalLabel: "Gesamtbetrag",
            AmountPaidLabel: "Bezahlt",
            AmountDueLabel: "Offen",
            PaymentMethodLabel: "Zahlungsart",
            PaymentReferenceLabel: "Referenz",
            PaymentInfoLabel: "Zahlungsinformationen",
            NotesLabel: "Notizen",
            FooterText: "Vielen Dank für Ihr Vertrauen. Diese Rechnung wurde automatisch erstellt.",
            SignatureLabel: "Unterschrift",
            PaymentMethodBankTransfer: "Überweisung",
            PaymentMethodCash: "Barzahlung",
            PaymentMethodCard: "Karte",
            PaymentMethodDirectDebit: "Lastschrift",
            PaymentMethodBizum: "Bizum",
            PaymentMethodOther: "Sonstige"),

        "hr" => new InvoicePdfLabels(
            Title: "Račun",
            CustomerLabel: "Klijent",
            PhoneLabel: "Telefon",
            EmailLabel: "Email",
            DateLabel: "Datum",
            DueDateLabel: "Dospijeće",
            ItemColumn: "Opis",
            QuantityColumn: "Količina",
            UnitPriceColumn: "Jed. cijena",
            DiscountColumn: "Popust (%)",
            TaxColumn: "PDV (%)",
            WithholdingColumn: "Porez po odbitku (%)",
            TotalColumn: "Ukupno",
            SubTotalLabel: "Podzbroj",
            TaxTotalLabel: "Ukupni porez",
            WithholdingTotalLabel: "Ukupni odbitak",
            GrandTotalLabel: "Sveukupno",
            AmountPaidLabel: "Plaćeno",
            AmountDueLabel: "Preostalo",
            PaymentMethodLabel: "Način plaćanja",
            PaymentReferenceLabel: "Referenca",
            PaymentInfoLabel: "Informacije o plaćanju",
            NotesLabel: "Napomene",
            FooterText: "Hvala na povjerenju. Ovaj račun je automatski generiran.",
            SignatureLabel: "Potpis",
            PaymentMethodBankTransfer: "Bankovni prijenos",
            PaymentMethodCash: "Gotovina",
            PaymentMethodCard: "Kartica",
            PaymentMethodDirectDebit: "Izravno terećenje",
            PaymentMethodBizum: "Bizum",
            PaymentMethodOther: "Ostalo"),

        _ => new InvoicePdfLabels(
            Title: "Invoice",
            CustomerLabel: "Customer",
            PhoneLabel: "Phone",
            EmailLabel: "Email",
            DateLabel: "Date",
            DueDateLabel: "Due Date",
            ItemColumn: "Description",
            QuantityColumn: "Qty",
            UnitPriceColumn: "Unit Price",
            DiscountColumn: "Disc. %",
            TaxColumn: "Tax (%)",
            WithholdingColumn: "Withholding (%)",
            TotalColumn: "Total",
            SubTotalLabel: "Subtotal",
            TaxTotalLabel: "Tax Total",
            WithholdingTotalLabel: "Withholding Total",
            GrandTotalLabel: "Grand Total",
            AmountPaidLabel: "Amount Paid",
            AmountDueLabel: "Amount Due",
            PaymentMethodLabel: "Payment Method",
            PaymentReferenceLabel: "Reference",
            PaymentInfoLabel: "Payment Information",
            NotesLabel: "Notes",
            FooterText: "Thank you for your trust. This invoice has been automatically generated.",
            SignatureLabel: "Signature",
            PaymentMethodBankTransfer: "Bank Transfer",
            PaymentMethodCash: "Cash",
            PaymentMethodCard: "Card",
            PaymentMethodDirectDebit: "Direct Debit",
            PaymentMethodBizum: "Bizum",
            PaymentMethodOther: "Other")
    };
}
