# Traefik dynamic configuration for local HTTPS with self-signed cert

http:
  routers:
    budgexaapi:
      rule: "Host(`api.localhost`)"
      entryPoints:
        - websecure
      service: budgexaapi
      tls:
        certResolver: selfsigned
    budgexaclient:
      rule: "Host(`localhost`)"
      entryPoints:
        - websecure
      service: budgexaclient
      tls:
        certResolver: selfsigned
    http-catchall:
      entryPoints:
        - web
      rule: "HostRegexp(`{any:.+}`)"
      middlewares:
        - redirect-to-https
      service: noop@internal

  services:
    budgexaapi:
      loadBalancer:
        servers:
          - url: "http://budgexa-api:80"
    budgexaclient:
      loadBalancer:
        servers:
          - url: "http://budgexa-client:80"

  middlewares:
    redirect-to-https:
      redirectScheme:
        scheme: https
        permanent: true

certificatesResolvers:
  selfsigned:
    selfSigned: {}
