// <auto-generated />
using System;
using Budgexa.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Budgexa.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Budgexa.Domain.Entities.Budget", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0);

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(5);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(1);

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(3);

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nchar(3)")
                        .HasColumnOrder(11)
                        .IsFixedLength();

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(6);

                    b.Property<DateOnly>("IssueDate")
                        .HasColumnType("date")
                        .HasColumnOrder(9);

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnOrder(15);

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnOrder(8);

                    b.Property<Guid>("StatusId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(7);

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnOrder(12);

                    b.Property<decimal>("TaxAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnOrder(13);

                    b.Property<string>("TermsAndConditions")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnOrder(16);

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnOrder(14);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(2);

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(4);

                    b.Property<DateOnly?>("ValidUntil")
                        .HasColumnType("date")
                        .HasColumnOrder(10);

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("StatusId");

                    b.HasIndex("CompanyId", "Number")
                        .IsUnique();

                    b.ToTable("Budgets", (string)null);
                });

            modelBuilder.Entity("Budgexa.Domain.Entities.BudgetLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0);

                    b.Property<Guid>("BudgetId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnOrder(4);

                    b.Property<decimal>("DiscountPercentage")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnOrder(8);

                    b.Property<Guid?>("ItemId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(2);

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnOrder(6);

                    b.Property<int>("SortOrder")
                        .HasColumnType("int")
                        .HasColumnOrder(3);

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnOrder(10);

                    b.Property<decimal>("TaxAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnOrder(11);

                    b.Property<decimal>("TaxRate")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnOrder(9);

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnOrder(12);

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnOrder(5);

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnOrder(7);

                    b.HasKey("Id");

                    b.HasIndex("BudgetId");

                    b.HasIndex("ItemId");

                    b.ToTable("BudgetLines", (string)null);
                });

            modelBuilder.Entity("Budgexa.Domain.Entities.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(1);

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(3);

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnOrder(6);

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnOrder(8);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnOrder(5);

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnOrder(7);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(2);

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(4);

                    b.HasKey("Id");

                    b.ToTable("Companies", (string)null);
                });

            modelBuilder.Entity("Budgexa.Domain.Entities.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0);

                    b.Property<string>("AddressLine")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnOrder(12);

                    b.Property<string>("City")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnOrder(13);

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(5);

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnOrder(16);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(1);

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(3);

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnOrder(10);

                    b.Property<string>("LegalName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnOrder(7);

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnOrder(17);

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnOrder(11);

                    b.Property<string>("PostalCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnOrder(14);

                    b.Property<string>("Province")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnOrder(15);

                    b.Property<Guid>("StatusId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(6);

                    b.Property<string>("TaxId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnOrder(9);

                    b.Property<string>("TradeName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnOrder(8);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(2);

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(4);

                    b.HasKey("Id");

                    b.HasIndex("StatusId");

                    b.HasIndex("CompanyId", "TaxId")
                        .IsUnique();

                    b.ToTable("Customers", (string)null);
                });

            modelBuilder.Entity("Budgexa.Domain.Entities.Invoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0);

                    b.Property<decimal>("AmountPaid")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnOrder(18);

                    b.Property<Guid?>("BudgetId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(8);

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(5);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(1);

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(3);

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nchar(3)")
                        .HasColumnOrder(13)
                        .IsFixedLength();

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(6);

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("date")
                        .HasColumnOrder(12);

                    b.Property<DateOnly>("IssueDate")
                        .HasColumnType("date")
                        .HasColumnOrder(11);

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnOrder(21);

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnOrder(10);

                    b.Property<int?>("PaymentMethod")
                        .HasColumnType("int")
                        .HasColumnOrder(19);

                    b.Property<string>("PaymentReference")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnOrder(20);

                    b.Property<string>("Series")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnOrder(9);

                    b.Property<Guid>("StatusId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(7);

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnOrder(14);

                    b.Property<decimal>("TaxAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnOrder(15);

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnOrder(17);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(2);

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(4);

                    b.Property<decimal>("WithholdingAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnOrder(16);

                    b.HasKey("Id");

                    b.HasIndex("BudgetId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("StatusId");

                    b.HasIndex("CompanyId", "Series", "Number")
                        .IsUnique();

                    b.ToTable("Invoices", (string)null);
                });

            modelBuilder.Entity("Budgexa.Domain.Entities.InvoiceLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnOrder(4);

                    b.Property<decimal>("DiscountPercentage")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnOrder(8);

                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(1);

                    b.Property<Guid?>("ItemId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(2);

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnOrder(6);

                    b.Property<int>("SortOrder")
                        .HasColumnType("int")
                        .HasColumnOrder(3);

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnOrder(11);

                    b.Property<decimal>("TaxAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnOrder(12);

                    b.Property<decimal>("TaxRate")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnOrder(9);

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnOrder(14);

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnOrder(5);

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnOrder(7);

                    b.Property<decimal>("WithholdingAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnOrder(13);

                    b.Property<decimal>("WithholdingRate")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnOrder(10);

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.HasIndex("ItemId");

                    b.ToTable("InvoiceLines", (string)null);
                });

            modelBuilder.Entity("Budgexa.Domain.Entities.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0);

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(5);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(1);

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(3);

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nchar(3)")
                        .HasColumnOrder(14)
                        .IsFixedLength();

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnOrder(9);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnOrder(8);

                    b.Property<string>("Sku")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnOrder(7);

                    b.Property<Guid>("StatusId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(6);

                    b.Property<decimal>("TaxRate")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnOrder(13);

                    b.Property<int>("Type")
                        .HasColumnType("int")
                        .HasColumnOrder(10);

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnOrder(11);

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnOrder(12);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(2);

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(4);

                    b.HasKey("Id");

                    b.HasIndex("StatusId");

                    b.HasIndex("CompanyId", "Sku")
                        .IsUnique()
                        .HasFilter("[Sku] IS NOT NULL");

                    b.ToTable("Items", (string)null);
                });

            modelBuilder.Entity("Budgexa.Domain.Entities.Language", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Languages", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("b2c1d3e4-f5a6-4b7c-8d9e-0f1a2b3c4d5e"),
                            Code = "en",
                            Name = "English"
                        },
                        new
                        {
                            Id = new Guid("c3d2e1f4-a5b6-4c7d-8e9f-0a1b2c3d4e5f"),
                            Code = "es",
                            Name = "Spanish"
                        },
                        new
                        {
                            Id = new Guid("d4e3f2a1-b5c6-4d7e-8f9a-0b1c2d3e4f5a"),
                            Code = "de",
                            Name = "German"
                        },
                        new
                        {
                            Id = new Guid("e5f4a3b2-c6d7-4e8f-9a0b-1c2d3e4f5a6b"),
                            Code = "hr",
                            Name = "Croatian"
                        });
                });

            modelBuilder.Entity("Budgexa.Domain.Entities.LanguageTranslation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LanguageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Translation")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("TranslationLanguageId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.HasIndex("TranslationLanguageId");

                    b.ToTable("LanguageTranslations", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1b2c3d4-e5f6-4a7b-8c9d-0e1f2a3b4c5d"),
                            LanguageId = new Guid("b2c1d3e4-f5a6-4b7c-8d9e-0f1a2b3c4d5e"),
                            Translation = "English",
                            TranslationLanguageId = new Guid("b2c1d3e4-f5a6-4b7c-8d9e-0f1a2b3c4d5e")
                        },
                        new
                        {
                            Id = new Guid("b2c3d4e5-f6a7-4b8c-9d0e-1f2a3b4c5d6e"),
                            LanguageId = new Guid("b2c1d3e4-f5a6-4b7c-8d9e-0f1a2b3c4d5e"),
                            Translation = "Inglés",
                            TranslationLanguageId = new Guid("c3d2e1f4-a5b6-4c7d-8e9f-0a1b2c3d4e5f")
                        },
                        new
                        {
                            Id = new Guid("c3d4e5f6-a7b8-4c9d-0e1f-2a3b4c5d6e7f"),
                            LanguageId = new Guid("b2c1d3e4-f5a6-4b7c-8d9e-0f1a2b3c4d5e"),
                            Translation = "Englisch",
                            TranslationLanguageId = new Guid("d4e3f2a1-b5c6-4d7e-8f9a-0b1c2d3e4f5a")
                        },
                        new
                        {
                            Id = new Guid("d4e5f6a7-b8c9-4d0e-1f2a-3b4c5d6e7f8a"),
                            LanguageId = new Guid("b2c1d3e4-f5a6-4b7c-8d9e-0f1a2b3c4d5e"),
                            Translation = "Engleski",
                            TranslationLanguageId = new Guid("e5f4a3b2-c6d7-4e8f-9a0b-1c2d3e4f5a6b")
                        },
                        new
                        {
                            Id = new Guid("e5f6a7b8-c9d0-4e1f-2a3b-4c5d6e7f8a9b"),
                            LanguageId = new Guid("c3d2e1f4-a5b6-4c7d-8e9f-0a1b2c3d4e5f"),
                            Translation = "Spanish",
                            TranslationLanguageId = new Guid("b2c1d3e4-f5a6-4b7c-8d9e-0f1a2b3c4d5e")
                        },
                        new
                        {
                            Id = new Guid("f6a7b8c9-d0e1-4f2a-3b4c-5d6e7f8a9b0c"),
                            LanguageId = new Guid("c3d2e1f4-a5b6-4c7d-8e9f-0a1b2c3d4e5f"),
                            Translation = "Español",
                            TranslationLanguageId = new Guid("c3d2e1f4-a5b6-4c7d-8e9f-0a1b2c3d4e5f")
                        },
                        new
                        {
                            Id = new Guid("a7b8c9d0-e1f2-4a3b-4c5d-6e7f8a9b0c1d"),
                            LanguageId = new Guid("c3d2e1f4-a5b6-4c7d-8e9f-0a1b2c3d4e5f"),
                            Translation = "Spanisch",
                            TranslationLanguageId = new Guid("d4e3f2a1-b5c6-4d7e-8f9a-0b1c2d3e4f5a")
                        },
                        new
                        {
                            Id = new Guid("b8c9d0e1-f2a3-4b4c-5d6e-7f8a9b0c1d2e"),
                            LanguageId = new Guid("c3d2e1f4-a5b6-4c7d-8e9f-0a1b2c3d4e5f"),
                            Translation = "Španjolski",
                            TranslationLanguageId = new Guid("e5f4a3b2-c6d7-4e8f-9a0b-1c2d3e4f5a6b")
                        },
                        new
                        {
                            Id = new Guid("c9d0e1f2-a3b4-4c5d-6e7f-8a9b0c1d2e3f"),
                            LanguageId = new Guid("d4e3f2a1-b5c6-4d7e-8f9a-0b1c2d3e4f5a"),
                            Translation = "German",
                            TranslationLanguageId = new Guid("b2c1d3e4-f5a6-4b7c-8d9e-0f1a2b3c4d5e")
                        },
                        new
                        {
                            Id = new Guid("d0e1f2a3-b4c5-4d6e-7f8a-9b0c1d2e3f4a"),
                            LanguageId = new Guid("d4e3f2a1-b5c6-4d7e-8f9a-0b1c2d3e4f5a"),
                            Translation = "Alemán",
                            TranslationLanguageId = new Guid("c3d2e1f4-a5b6-4c7d-8e9f-0a1b2c3d4e5f")
                        },
                        new
                        {
                            Id = new Guid("e1f2a3b4-c5d6-4e7f-8a9b-0c1d2e3f4a5b"),
                            LanguageId = new Guid("d4e3f2a1-b5c6-4d7e-8f9a-0b1c2d3e4f5a"),
                            Translation = "Deutsch",
                            TranslationLanguageId = new Guid("d4e3f2a1-b5c6-4d7e-8f9a-0b1c2d3e4f5a")
                        },
                        new
                        {
                            Id = new Guid("f2a3b4c5-d6e7-4f8a-9b0c-1d2e3f4a5b6c"),
                            LanguageId = new Guid("d4e3f2a1-b5c6-4d7e-8f9a-0b1c2d3e4f5a"),
                            Translation = "Njemački",
                            TranslationLanguageId = new Guid("e5f4a3b2-c6d7-4e8f-9a0b-1c2d3e4f5a6b")
                        },
                        new
                        {
                            Id = new Guid("a3b4c5d6-e7f8-4a9b-0c1d-2e3f4a5b6c7d"),
                            LanguageId = new Guid("e5f4a3b2-c6d7-4e8f-9a0b-1c2d3e4f5a6b"),
                            Translation = "Croatian",
                            TranslationLanguageId = new Guid("b2c1d3e4-f5a6-4b7c-8d9e-0f1a2b3c4d5e")
                        },
                        new
                        {
                            Id = new Guid("b4c5d6e7-f8a9-4b0c-1d2e-3f4a5b6c7d8e"),
                            LanguageId = new Guid("e5f4a3b2-c6d7-4e8f-9a0b-1c2d3e4f5a6b"),
                            Translation = "Croata",
                            TranslationLanguageId = new Guid("c3d2e1f4-a5b6-4c7d-8e9f-0a1b2c3d4e5f")
                        },
                        new
                        {
                            Id = new Guid("c5d6e7f8-a9b0-4c1d-2e3f-4a5b6c7d8e9f"),
                            LanguageId = new Guid("e5f4a3b2-c6d7-4e8f-9a0b-1c2d3e4f5a6b"),
                            Translation = "Kroatisch",
                            TranslationLanguageId = new Guid("d4e3f2a1-b5c6-4d7e-8f9a-0b1c2d3e4f5a")
                        },
                        new
                        {
                            Id = new Guid("d6e7f8a9-b0c1-4d2e-3f4a-5b6c7d8e9f0a"),
                            LanguageId = new Guid("e5f4a3b2-c6d7-4e8f-9a0b-1c2d3e4f5a6b"),
                            Translation = "Hrvatski",
                            TranslationLanguageId = new Guid("e5f4a3b2-c6d7-4e8f-9a0b-1c2d3e4f5a6b")
                        });
                });

            modelBuilder.Entity("Budgexa.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReplacedByToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Budgexa.Domain.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("9f3c2a6e-8b71-4b8d-9c2a-5f6e3d1a7c90"),
                            Name = "freelance"
                        },
                        new
                        {
                            Id = new Guid("d4a1f9b2-3c7e-4e5a-8a91-2b6c0f7d8e13"),
                            Name = "administrator"
                        },
                        new
                        {
                            Id = new Guid("6b2e4c9a-1f83-4d7b-b2a5-9e0c3f6a1d74"),
                            Name = "superadministrator"
                        });
                });

            modelBuilder.Entity("Budgexa.Domain.Entities.Status", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Group")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Statuses", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1e2b3c4-d5f6-4a7b-8c9d-0e1f2a3b4c5d"),
                            Group = "Base",
                            Name = "New",
                            Value = 1
                        },
                        new
                        {
                            Id = new Guid("e5d4c3b2-a1f0-4e9d-8c7b-6a5f4e3d2c1b"),
                            Group = "Base",
                            Name = "Delete",
                            Value = 2
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-4111-8111-111111111111"),
                            Group = "Budget",
                            Name = "Draft",
                            Value = 1
                        },
                        new
                        {
                            Id = new Guid("22222222-1111-4111-8111-111111111111"),
                            Group = "Budget",
                            Name = "Sent",
                            Value = 2
                        },
                        new
                        {
                            Id = new Guid("33333333-1111-4111-8111-111111111111"),
                            Group = "Budget",
                            Name = "Approved",
                            Value = 3
                        },
                        new
                        {
                            Id = new Guid("44444444-1111-4111-8111-111111111111"),
                            Group = "Budget",
                            Name = "Rejected",
                            Value = 4
                        },
                        new
                        {
                            Id = new Guid("55555555-1111-4111-8111-111111111111"),
                            Group = "Budget",
                            Name = "Expired",
                            Value = 5
                        },
                        new
                        {
                            Id = new Guid("66666666-1111-4111-8111-111111111111"),
                            Group = "Budget",
                            Name = "Invoiced",
                            Value = 6
                        },
                        new
                        {
                            Id = new Guid("11111111-2222-4222-8222-222222222222"),
                            Group = "Invoice",
                            Name = "Draft",
                            Value = 1
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-4222-8222-222222222222"),
                            Group = "Invoice",
                            Name = "Issued",
                            Value = 2
                        },
                        new
                        {
                            Id = new Guid("33333333-2222-4222-8222-222222222222"),
                            Group = "Invoice",
                            Name = "PartiallyPaid",
                            Value = 3
                        },
                        new
                        {
                            Id = new Guid("44444444-2222-4222-8222-222222222222"),
                            Group = "Invoice",
                            Name = "Paid",
                            Value = 4
                        },
                        new
                        {
                            Id = new Guid("55555555-2222-4222-8222-222222222222"),
                            Group = "Invoice",
                            Name = "Overdue",
                            Value = 5
                        },
                        new
                        {
                            Id = new Guid("66666666-2222-4222-8222-222222222222"),
                            Group = "Invoice",
                            Name = "Cancelled",
                            Value = 6
                        });
                });

            modelBuilder.Entity("Budgexa.Domain.Entities.StatusTranslation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LanguageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StatusId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Translation")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.HasIndex("StatusId");

                    b.ToTable("StatusTranslations", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("b1e2c3d4-5f6a-4b7c-8d9e-0f1a2b3c4d5e"),
                            LanguageId = new Guid("b2c1d3e4-f5a6-4b7c-8d9e-0f1a2b3c4d5e"),
                            StatusId = new Guid("a1e2b3c4-d5f6-4a7b-8c9d-0e1f2a3b4c5d"),
                            Translation = "New"
                        },
                        new
                        {
                            Id = new Guid("c2d3e4f5-a6b7-4c8d-9e0f-1a2b3c4d5e6f"),
                            LanguageId = new Guid("c3d2e1f4-a5b6-4c7d-8e9f-0a1b2c3d4e5f"),
                            StatusId = new Guid("a1e2b3c4-d5f6-4a7b-8c9d-0e1f2a3b4c5d"),
                            Translation = "Nuevo"
                        },
                        new
                        {
                            Id = new Guid("d3e4f5a6-b7c8-4d9e-0f1a-2b3c4d5e6f7a"),
                            LanguageId = new Guid("d4e3f2a1-b5c6-4d7e-8f9a-0b1c2d3e4f5a"),
                            StatusId = new Guid("a1e2b3c4-d5f6-4a7b-8c9d-0e1f2a3b4c5d"),
                            Translation = "Neu"
                        },
                        new
                        {
                            Id = new Guid("e4f5a6b7-c8d9-4e0f-1a2b-3c4d5e6f7a8b"),
                            LanguageId = new Guid("e5f4a3b2-c6d7-4e8f-9a0b-1c2d3e4f5a6b"),
                            StatusId = new Guid("a1e2b3c4-d5f6-4a7b-8c9d-0e1f2a3b4c5d"),
                            Translation = "Novi"
                        },
                        new
                        {
                            Id = new Guid("f5a6b7c8-d9e0-4f1a-2b3c-4d5e6f7a8b9c"),
                            LanguageId = new Guid("b2c1d3e4-f5a6-4b7c-8d9e-0f1a2b3c4d5e"),
                            StatusId = new Guid("e5d4c3b2-a1f0-4e9d-8c7b-6a5f4e3d2c1b"),
                            Translation = "Delete"
                        },
                        new
                        {
                            Id = new Guid("a6b7c8d9-e0f1-4a2b-3c4d-5e6f7a8b9c0d"),
                            LanguageId = new Guid("c3d2e1f4-a5b6-4c7d-8e9f-0a1b2c3d4e5f"),
                            StatusId = new Guid("e5d4c3b2-a1f0-4e9d-8c7b-6a5f4e3d2c1b"),
                            Translation = "Eliminar"
                        },
                        new
                        {
                            Id = new Guid("b7c8d9e0-f1a2-4b3c-4d5e-6f7a8b9c0d1e"),
                            LanguageId = new Guid("d4e3f2a1-b5c6-4d7e-8f9a-0b1c2d3e4f5a"),
                            StatusId = new Guid("e5d4c3b2-a1f0-4e9d-8c7b-6a5f4e3d2c1b"),
                            Translation = "Löschen"
                        },
                        new
                        {
                            Id = new Guid("c8d9e0f1-a2b3-4c4d-5e6f-7a8b9c0d1e2f"),
                            LanguageId = new Guid("e5f4a3b2-c6d7-4e8f-9a0b-1c2d3e4f5a6b"),
                            StatusId = new Guid("e5d4c3b2-a1f0-4e9d-8c7b-6a5f4e3d2c1b"),
                            Translation = "Izbriši"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-4111-8111-aaaaaaaaaaa1"),
                            LanguageId = new Guid("b2c1d3e4-f5a6-4b7c-8d9e-0f1a2b3c4d5e"),
                            StatusId = new Guid("11111111-1111-4111-8111-111111111111"),
                            Translation = "Draft"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-4111-8111-aaaaaaaaaaa2"),
                            LanguageId = new Guid("c3d2e1f4-a5b6-4c7d-8e9f-0a1b2c3d4e5f"),
                            StatusId = new Guid("11111111-1111-4111-8111-111111111111"),
                            Translation = "Borrador"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-4111-8111-aaaaaaaaaaa3"),
                            LanguageId = new Guid("d4e3f2a1-b5c6-4d7e-8f9a-0b1c2d3e4f5a"),
                            StatusId = new Guid("11111111-1111-4111-8111-111111111111"),
                            Translation = "Entwurf"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-4111-8111-aaaaaaaaaaa4"),
                            LanguageId = new Guid("e5f4a3b2-c6d7-4e8f-9a0b-1c2d3e4f5a6b"),
                            StatusId = new Guid("11111111-1111-4111-8111-111111111111"),
                            Translation = "Nacrt"
                        },
                        new
                        {
                            Id = new Guid("22222222-1111-4111-8111-aaaaaaaaaaa1"),
                            LanguageId = new Guid("b2c1d3e4-f5a6-4b7c-8d9e-0f1a2b3c4d5e"),
                            StatusId = new Guid("22222222-1111-4111-8111-111111111111"),
                            Translation = "Sent"
                        },
                        new
                        {
                            Id = new Guid("22222222-1111-4111-8111-aaaaaaaaaaa2"),
                            LanguageId = new Guid("c3d2e1f4-a5b6-4c7d-8e9f-0a1b2c3d4e5f"),
                            StatusId = new Guid("22222222-1111-4111-8111-111111111111"),
                            Translation = "Enviado"
                        },
                        new
                        {
                            Id = new Guid("22222222-1111-4111-8111-aaaaaaaaaaa3"),
                            LanguageId = new Guid("d4e3f2a1-b5c6-4d7e-8f9a-0b1c2d3e4f5a"),
                            StatusId = new Guid("22222222-1111-4111-8111-111111111111"),
                            Translation = "Gesendet"
                        },
                        new
                        {
                            Id = new Guid("22222222-1111-4111-8111-aaaaaaaaaaa4"),
                            LanguageId = new Guid("e5f4a3b2-c6d7-4e8f-9a0b-1c2d3e4f5a6b"),
                            StatusId = new Guid("22222222-1111-4111-8111-111111111111"),
                            Translation = "Poslano"
                        },
                        new
                        {
                            Id = new Guid("33333333-1111-4111-8111-aaaaaaaaaaa1"),
                            LanguageId = new Guid("b2c1d3e4-f5a6-4b7c-8d9e-0f1a2b3c4d5e"),
                            StatusId = new Guid("33333333-1111-4111-8111-111111111111"),
                            Translation = "Approved"
                        },
                        new
                        {
                            Id = new Guid("33333333-1111-4111-8111-aaaaaaaaaaa2"),
                            LanguageId = new Guid("c3d2e1f4-a5b6-4c7d-8e9f-0a1b2c3d4e5f"),
                            StatusId = new Guid("33333333-1111-4111-8111-111111111111"),
                            Translation = "Aprobado"
                        },
                        new
                        {
                            Id = new Guid("33333333-1111-4111-8111-aaaaaaaaaaa3"),
                            LanguageId = new Guid("d4e3f2a1-b5c6-4d7e-8f9a-0b1c2d3e4f5a"),
                            StatusId = new Guid("33333333-1111-4111-8111-111111111111"),
                            Translation = "Genehmigt"
                        },
                        new
                        {
                            Id = new Guid("33333333-1111-4111-8111-aaaaaaaaaaa4"),
                            LanguageId = new Guid("e5f4a3b2-c6d7-4e8f-9a0b-1c2d3e4f5a6b"),
                            StatusId = new Guid("33333333-1111-4111-8111-111111111111"),
                            Translation = "Odobreno"
                        },
                        new
                        {
                            Id = new Guid("44444444-1111-4111-8111-aaaaaaaaaaa1"),
                            LanguageId = new Guid("b2c1d3e4-f5a6-4b7c-8d9e-0f1a2b3c4d5e"),
                            StatusId = new Guid("44444444-1111-4111-8111-111111111111"),
                            Translation = "Rejected"
                        },
                        new
                        {
                            Id = new Guid("44444444-1111-4111-8111-aaaaaaaaaaa2"),
                            LanguageId = new Guid("c3d2e1f4-a5b6-4c7d-8e9f-0a1b2c3d4e5f"),
                            StatusId = new Guid("44444444-1111-4111-8111-111111111111"),
                            Translation = "Rechazado"
                        },
                        new
                        {
                            Id = new Guid("44444444-1111-4111-8111-aaaaaaaaaaa3"),
                            LanguageId = new Guid("d4e3f2a1-b5c6-4d7e-8f9a-0b1c2d3e4f5a"),
                            StatusId = new Guid("44444444-1111-4111-8111-111111111111"),
                            Translation = "Abgelehnt"
                        },
                        new
                        {
                            Id = new Guid("44444444-1111-4111-8111-aaaaaaaaaaa4"),
                            LanguageId = new Guid("e5f4a3b2-c6d7-4e8f-9a0b-1c2d3e4f5a6b"),
                            StatusId = new Guid("44444444-1111-4111-8111-111111111111"),
                            Translation = "Odbijeno"
                        },
                        new
                        {
                            Id = new Guid("55555555-1111-4111-8111-aaaaaaaaaaa1"),
                            LanguageId = new Guid("b2c1d3e4-f5a6-4b7c-8d9e-0f1a2b3c4d5e"),
                            StatusId = new Guid("55555555-1111-4111-8111-111111111111"),
                            Translation = "Expired"
                        },
                        new
                        {
                            Id = new Guid("55555555-1111-4111-8111-aaaaaaaaaaa2"),
                            LanguageId = new Guid("c3d2e1f4-a5b6-4c7d-8e9f-0a1b2c3d4e5f"),
                            StatusId = new Guid("55555555-1111-4111-8111-111111111111"),
                            Translation = "Caducado"
                        },
                        new
                        {
                            Id = new Guid("55555555-1111-4111-8111-aaaaaaaaaaa3"),
                            LanguageId = new Guid("d4e3f2a1-b5c6-4d7e-8f9a-0b1c2d3e4f5a"),
                            StatusId = new Guid("55555555-1111-4111-8111-111111111111"),
                            Translation = "Abgelaufen"
                        },
                        new
                        {
                            Id = new Guid("55555555-1111-4111-8111-aaaaaaaaaaa4"),
                            LanguageId = new Guid("e5f4a3b2-c6d7-4e8f-9a0b-1c2d3e4f5a6b"),
                            StatusId = new Guid("55555555-1111-4111-8111-111111111111"),
                            Translation = "Isteklo"
                        },
                        new
                        {
                            Id = new Guid("66666666-1111-4111-8111-aaaaaaaaaaa1"),
                            LanguageId = new Guid("b2c1d3e4-f5a6-4b7c-8d9e-0f1a2b3c4d5e"),
                            StatusId = new Guid("66666666-1111-4111-8111-111111111111"),
                            Translation = "Invoiced"
                        },
                        new
                        {
                            Id = new Guid("66666666-1111-4111-8111-aaaaaaaaaaa2"),
                            LanguageId = new Guid("c3d2e1f4-a5b6-4c7d-8e9f-0a1b2c3d4e5f"),
                            StatusId = new Guid("66666666-1111-4111-8111-111111111111"),
                            Translation = "Facturado"
                        },
                        new
                        {
                            Id = new Guid("66666666-1111-4111-8111-aaaaaaaaaaa3"),
                            LanguageId = new Guid("d4e3f2a1-b5c6-4d7e-8f9a-0b1c2d3e4f5a"),
                            StatusId = new Guid("66666666-1111-4111-8111-111111111111"),
                            Translation = "Fakturiert"
                        },
                        new
                        {
                            Id = new Guid("66666666-1111-4111-8111-aaaaaaaaaaa4"),
                            LanguageId = new Guid("e5f4a3b2-c6d7-4e8f-9a0b-1c2d3e4f5a6b"),
                            StatusId = new Guid("66666666-1111-4111-8111-111111111111"),
                            Translation = "Fakturirano"
                        },
                        new
                        {
                            Id = new Guid("11111111-2222-4222-8222-bbbbbbbbbbb1"),
                            LanguageId = new Guid("b2c1d3e4-f5a6-4b7c-8d9e-0f1a2b3c4d5e"),
                            StatusId = new Guid("11111111-2222-4222-8222-222222222222"),
                            Translation = "Draft"
                        },
                        new
                        {
                            Id = new Guid("11111111-2222-4222-8222-bbbbbbbbbbb2"),
                            LanguageId = new Guid("c3d2e1f4-a5b6-4c7d-8e9f-0a1b2c3d4e5f"),
                            StatusId = new Guid("11111111-2222-4222-8222-222222222222"),
                            Translation = "Borrador"
                        },
                        new
                        {
                            Id = new Guid("11111111-2222-4222-8222-bbbbbbbbbbb3"),
                            LanguageId = new Guid("d4e3f2a1-b5c6-4d7e-8f9a-0b1c2d3e4f5a"),
                            StatusId = new Guid("11111111-2222-4222-8222-222222222222"),
                            Translation = "Entwurf"
                        },
                        new
                        {
                            Id = new Guid("11111111-2222-4222-8222-bbbbbbbbbbb4"),
                            LanguageId = new Guid("e5f4a3b2-c6d7-4e8f-9a0b-1c2d3e4f5a6b"),
                            StatusId = new Guid("11111111-2222-4222-8222-222222222222"),
                            Translation = "Nacrt"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-4222-8222-bbbbbbbbbbb1"),
                            LanguageId = new Guid("b2c1d3e4-f5a6-4b7c-8d9e-0f1a2b3c4d5e"),
                            StatusId = new Guid("22222222-2222-4222-8222-222222222222"),
                            Translation = "Issued"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-4222-8222-bbbbbbbbbbb2"),
                            LanguageId = new Guid("c3d2e1f4-a5b6-4c7d-8e9f-0a1b2c3d4e5f"),
                            StatusId = new Guid("22222222-2222-4222-8222-222222222222"),
                            Translation = "Emitida"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-4222-8222-bbbbbbbbbbb3"),
                            LanguageId = new Guid("d4e3f2a1-b5c6-4d7e-8f9a-0b1c2d3e4f5a"),
                            StatusId = new Guid("22222222-2222-4222-8222-222222222222"),
                            Translation = "Ausgestellt"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-4222-8222-bbbbbbbbbbb4"),
                            LanguageId = new Guid("e5f4a3b2-c6d7-4e8f-9a0b-1c2d3e4f5a6b"),
                            StatusId = new Guid("22222222-2222-4222-8222-222222222222"),
                            Translation = "Izdano"
                        },
                        new
                        {
                            Id = new Guid("33333333-2222-4222-8222-bbbbbbbbbbb1"),
                            LanguageId = new Guid("b2c1d3e4-f5a6-4b7c-8d9e-0f1a2b3c4d5e"),
                            StatusId = new Guid("33333333-2222-4222-8222-222222222222"),
                            Translation = "Partially paid"
                        },
                        new
                        {
                            Id = new Guid("33333333-2222-4222-8222-bbbbbbbbbbb2"),
                            LanguageId = new Guid("c3d2e1f4-a5b6-4c7d-8e9f-0a1b2c3d4e5f"),
                            StatusId = new Guid("33333333-2222-4222-8222-222222222222"),
                            Translation = "Parcialmente pagada"
                        },
                        new
                        {
                            Id = new Guid("33333333-2222-4222-8222-bbbbbbbbbbb3"),
                            LanguageId = new Guid("d4e3f2a1-b5c6-4d7e-8f9a-0b1c2d3e4f5a"),
                            StatusId = new Guid("33333333-2222-4222-8222-222222222222"),
                            Translation = "Teilweise bezahlt"
                        },
                        new
                        {
                            Id = new Guid("33333333-2222-4222-8222-bbbbbbbbbbb4"),
                            LanguageId = new Guid("e5f4a3b2-c6d7-4e8f-9a0b-1c2d3e4f5a6b"),
                            StatusId = new Guid("33333333-2222-4222-8222-222222222222"),
                            Translation = "Djelomično plaćeno"
                        },
                        new
                        {
                            Id = new Guid("44444444-2222-4222-8222-bbbbbbbbbbb1"),
                            LanguageId = new Guid("b2c1d3e4-f5a6-4b7c-8d9e-0f1a2b3c4d5e"),
                            StatusId = new Guid("44444444-2222-4222-8222-222222222222"),
                            Translation = "Paid"
                        },
                        new
                        {
                            Id = new Guid("44444444-2222-4222-8222-bbbbbbbbbbb2"),
                            LanguageId = new Guid("c3d2e1f4-a5b6-4c7d-8e9f-0a1b2c3d4e5f"),
                            StatusId = new Guid("44444444-2222-4222-8222-222222222222"),
                            Translation = "Pagada"
                        },
                        new
                        {
                            Id = new Guid("44444444-2222-4222-8222-bbbbbbbbbbb3"),
                            LanguageId = new Guid("d4e3f2a1-b5c6-4d7e-8f9a-0b1c2d3e4f5a"),
                            StatusId = new Guid("44444444-2222-4222-8222-222222222222"),
                            Translation = "Bezahlt"
                        },
                        new
                        {
                            Id = new Guid("44444444-2222-4222-8222-bbbbbbbbbbb4"),
                            LanguageId = new Guid("e5f4a3b2-c6d7-4e8f-9a0b-1c2d3e4f5a6b"),
                            StatusId = new Guid("44444444-2222-4222-8222-222222222222"),
                            Translation = "Plaćeno"
                        },
                        new
                        {
                            Id = new Guid("55555555-2222-4222-8222-bbbbbbbbbbb1"),
                            LanguageId = new Guid("b2c1d3e4-f5a6-4b7c-8d9e-0f1a2b3c4d5e"),
                            StatusId = new Guid("55555555-2222-4222-8222-222222222222"),
                            Translation = "Overdue"
                        },
                        new
                        {
                            Id = new Guid("55555555-2222-4222-8222-bbbbbbbbbbb2"),
                            LanguageId = new Guid("c3d2e1f4-a5b6-4c7d-8e9f-0a1b2c3d4e5f"),
                            StatusId = new Guid("55555555-2222-4222-8222-222222222222"),
                            Translation = "Vencida"
                        },
                        new
                        {
                            Id = new Guid("55555555-2222-4222-8222-bbbbbbbbbbb3"),
                            LanguageId = new Guid("d4e3f2a1-b5c6-4d7e-8f9a-0b1c2d3e4f5a"),
                            StatusId = new Guid("55555555-2222-4222-8222-222222222222"),
                            Translation = "Überfällig"
                        },
                        new
                        {
                            Id = new Guid("55555555-2222-4222-8222-bbbbbbbbbbb4"),
                            LanguageId = new Guid("e5f4a3b2-c6d7-4e8f-9a0b-1c2d3e4f5a6b"),
                            StatusId = new Guid("55555555-2222-4222-8222-222222222222"),
                            Translation = "Dospjelo"
                        },
                        new
                        {
                            Id = new Guid("66666666-2222-4222-8222-bbbbbbbbbbb1"),
                            LanguageId = new Guid("b2c1d3e4-f5a6-4b7c-8d9e-0f1a2b3c4d5e"),
                            StatusId = new Guid("66666666-2222-4222-8222-222222222222"),
                            Translation = "Cancelled"
                        },
                        new
                        {
                            Id = new Guid("66666666-2222-4222-8222-bbbbbbbbbbb2"),
                            LanguageId = new Guid("c3d2e1f4-a5b6-4c7d-8e9f-0a1b2c3d4e5f"),
                            StatusId = new Guid("66666666-2222-4222-8222-222222222222"),
                            Translation = "Cancelada"
                        },
                        new
                        {
                            Id = new Guid("66666666-2222-4222-8222-bbbbbbbbbbb3"),
                            LanguageId = new Guid("d4e3f2a1-b5c6-4d7e-8f9a-0b1c2d3e4f5a"),
                            StatusId = new Guid("66666666-2222-4222-8222-222222222222"),
                            Translation = "Storniert"
                        },
                        new
                        {
                            Id = new Guid("66666666-2222-4222-8222-bbbbbbbbbbb4"),
                            LanguageId = new Guid("e5f4a3b2-c6d7-4e8f-9a0b-1c2d3e4f5a6b"),
                            StatusId = new Guid("66666666-2222-4222-8222-222222222222"),
                            Translation = "Otkazano"
                        });
                });

            modelBuilder.Entity("Budgexa.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0);

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(5);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(1);

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(3);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnOrder(8);

                    b.Property<int>("FailedLoginAttempts")
                        .HasColumnType("int")
                        .HasColumnOrder(12);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnOrder(10);

                    b.Property<Guid>("LanguageId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(6);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnOrder(11);

                    b.Property<DateTime?>("LockoutEnd")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(13);

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(9);

                    b.Property<Guid>("StatusId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(7);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(2);

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(4);

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("LanguageId");

                    b.HasIndex("StatusId");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Budgexa.Domain.Entities.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("Budgexa.Domain.Entities.Budget", b =>
                {
                    b.HasOne("Budgexa.Domain.Entities.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Budgexa.Domain.Entities.Customer", "Customer")
                        .WithMany("Budgets")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Budgexa.Domain.Entities.Status", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Customer");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("Budgexa.Domain.Entities.BudgetLine", b =>
                {
                    b.HasOne("Budgexa.Domain.Entities.Budget", "Budget")
                        .WithMany("Lines")
                        .HasForeignKey("BudgetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Budgexa.Domain.Entities.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Budget");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("Budgexa.Domain.Entities.Customer", b =>
                {
                    b.HasOne("Budgexa.Domain.Entities.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Budgexa.Domain.Entities.Status", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("Budgexa.Domain.Entities.Invoice", b =>
                {
                    b.HasOne("Budgexa.Domain.Entities.Budget", "Budget")
                        .WithMany("Invoices")
                        .HasForeignKey("BudgetId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Budgexa.Domain.Entities.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Budgexa.Domain.Entities.Customer", "Customer")
                        .WithMany("Invoices")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Budgexa.Domain.Entities.Status", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Budget");

                    b.Navigation("Company");

                    b.Navigation("Customer");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("Budgexa.Domain.Entities.InvoiceLine", b =>
                {
                    b.HasOne("Budgexa.Domain.Entities.Invoice", "Invoice")
                        .WithMany("Lines")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Budgexa.Domain.Entities.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Invoice");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("Budgexa.Domain.Entities.Item", b =>
                {
                    b.HasOne("Budgexa.Domain.Entities.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Budgexa.Domain.Entities.Status", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("Budgexa.Domain.Entities.LanguageTranslation", b =>
                {
                    b.HasOne("Budgexa.Domain.Entities.Language", "Language")
                        .WithMany("Translations")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Budgexa.Domain.Entities.Language", "TranslationLanguage")
                        .WithMany()
                        .HasForeignKey("TranslationLanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("TranslationLanguage");
                });

            modelBuilder.Entity("Budgexa.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("Budgexa.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Budgexa.Domain.Entities.StatusTranslation", b =>
                {
                    b.HasOne("Budgexa.Domain.Entities.Language", "Language")
                        .WithMany("StatusTranslations")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Budgexa.Domain.Entities.Status", "Status")
                        .WithMany("Translations")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("Budgexa.Domain.Entities.User", b =>
                {
                    b.HasOne("Budgexa.Domain.Entities.Company", "Company")
                        .WithMany("Users")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Budgexa.Domain.Entities.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Budgexa.Domain.Entities.Status", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Language");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("Budgexa.Domain.Entities.UserRole", b =>
                {
                    b.HasOne("Budgexa.Domain.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Budgexa.Domain.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Budgexa.Domain.Entities.Budget", b =>
                {
                    b.Navigation("Invoices");

                    b.Navigation("Lines");
                });

            modelBuilder.Entity("Budgexa.Domain.Entities.Company", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Budgexa.Domain.Entities.Customer", b =>
                {
                    b.Navigation("Budgets");

                    b.Navigation("Invoices");
                });

            modelBuilder.Entity("Budgexa.Domain.Entities.Invoice", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("Budgexa.Domain.Entities.Language", b =>
                {
                    b.Navigation("StatusTranslations");

                    b.Navigation("Translations");
                });

            modelBuilder.Entity("Budgexa.Domain.Entities.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Budgexa.Domain.Entities.Status", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("Budgexa.Domain.Entities.User", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
