# --- Etapa 1: Build ---
FROM node:22-alpine AS build

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .

RUN chmod +x node_modules/.bin/ng
RUN npx ng build --configuration production

# --- Etapa 2: Servir con Nginx ---
FROM nginx:alpine

COPY --from=build /app/dist/budgexa-client/browser /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80 443

CMD ["nginx", "-g", "daemon off;"]
